name: badge_case
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.2
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/image/
    - assets/json/

  fonts:
    - family: Gotham-Black
      fonts:
        - asset: assets/fonts/Gotham/Gotham-Black.otf

    - family: Gotham-Bold
      fonts:
        - asset: assets/fonts/Gotham/Gotham-Bold.otf

    - family: Gotham-Book
      fonts:
        - asset: assets/fonts/Gotham/Gotham-Book.otf

    - family: Gotham-Light
      fonts:
        - asset: assets/fonts/Gotham/Gotham-Light.otf

    - family: Gotham-Medium
      fonts:
        - asset: assets/fonts/Gotham/Gotham-Medium.otf
